### ISSUE TITLE
Should have support for custom plugins

### ISSUE THREAD

**Issue by SamCarlberg** [wpilibsuite/shuffleboard#102]
Plugins would have:

- A name
- A list of custom widgets
- A list of custom source types
- A list of custom data types

The name must always be set, but plugins can choose to define any or all of the custom lists.

We'll need to change `SourceType` away from an enum to an interface + util class, like `DataType`/`DataTypes`. Should probably also change `SourceType` to do data recording and playback, so we don't have to add custom code for each source type in the recording/playback classes.

We'd need to add UI stuff to load plugin jars or classes, as well as a simple dialog to show the currently loaded plugins.

Providing the plugin API would let us move classes into their own jars. All the stock widgets can be bundled into a `StockWidget` plugin, network table sources can be in a `NetworkTable Source` plugin, etc. Ideally the stock data types would also go into a plugin, but that would mean plugins would either need to be compiled with that jar to let the `@Description` annotation to function, forcing us to load that jar first to make sure the data type classes are loaded; or remove the `@Description` annotation entirely.

Because of this, I think we should keep the stock data types in the api jar (#101) to make sure all plugins can use all the data types provided by WPILib, but still split the stock widgets and data sources into plugins.

There are a few pain points like the network table tree widget that we use to display data in network tables and add widgets from. We may want to let source types provide a JavaFX node that we stick in a tab in the sources view.

**Comment by nightpool** [comment]
closed by #140
