### ISSUE TITLE
Widget gallery UI could use some work (borders perhaps?)

### ISSUE THREAD

**Issue by JLLeitschuh** [wpilibsuite/shuffleboard#106]
The widgets tab kind of looks sad. It might help to have borders around each component.

<img width="198" alt="screen shot 2017-08-07 at 4 15 25 pm" src="https://user-images.githubusercontent.com/1323708/29044055-ade0389e-7b8b-11e7-823d-ff72f459c12a.png">

As it is it the title isn't visually tied to the component.

Sorry if this is a duplicate issue.

**Comment by SamCarlberg** [comment]
This is how it looks for me (on `master`)

![screenshot from 2017-08-07 16 17 01](https://user-images.githubusercontent.com/6320992/29044104-dec1402a-7b8b-11e7-88cf-510b2b681014.png)

**Comment by JLLeitschuh** [comment]
The above image is what it looked like for me on master. I can try cleaning and rebuilding.

**Comment by SamCarlberg** [comment]
Looks like the CSS stylesheets didn't load for you

**Comment by JLLeitschuh** [comment]
I ran `./gradlew clean` and then `./gradlew run` (after fixing the `theMainClassName` like you did in your PR). It still looks like my picture above.

**Comment by SamCarlberg** [comment]
The console should have errors saying the stylesheets can't be loaded. Do you see that?

**Comment by nightpool** [comment]
@JLLeitschuh Make sure you're on c4d6565c, there were more changes related to style sheets in the PR. it sounds from your comment like you're on an older commit and just made the change manually.

**Comment by AustinShalit** [comment]
master has borders for me

**Comment by JLLeitschuh** [comment]
I'll check again tomorrow

**Comment by JLLeitschuh** [comment]
Looks fine now.... Weird.

**Comment by SamCarlberg** [comment]
Evan was correct: https://github.com/wpilibsuite/shuffleboard/issues/106#issuecomment-320783950
