### ISSUE TITLE
waitForNtcoreEvents() is broken

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/shuffleboard#117]
There is a race with the waitForNtcoreEvents method.  Take a look at this example code:

```
@Test
public void testDelete() {
  table.putString("testDelete", "value");
  // Listener could be fired here before we wait for a NetworkTable listener to be called!
  waitForNtcoreEvents();
  // ...
}

**Comment by JLLeitschuh** [comment]
Perhaps make `waitForNtcoreEvents` take a lambda function?

**Comment by AustinShalit** [comment]
That is exactly what I was thinking.

**Comment by nightpool** [comment]
Yes, this is a known issue. The fix was going to be mocking network tables, but the lambda seems like a reasonable solution too.
