### ISSUE TITLE
No way to restore default tabs

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/shuffleboard#129]
There should be a way to create the 'SmartDashboard' and 'LiveWindow' tabs from the UI

**Comment by SamCarlberg** [comment]
Do we need to? They're easy to create manually

**Comment by nightpool** [comment]
I think adding a "new..." menu item would resolve this for me.

**Comment by SamCarlberg** [comment]
Closed by #351 providing a "new layout" menu item to create a fresh set of tabs
