### ISSUE TITLE
"Network Table Tree" widget should be renamed to "NetworkTable Tree"

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/shuffleboard#132]
https://github.com/wpilibsuite/shuffleboard/blob/master/app/src/main/java/edu/wpi/first/shuffleboard/app/widget/NetworkTableTreeWidget.java#L26

**Comment by SamCarlberg** [comment]
This would be a backwards-incompatible change. Save files with "Network Table Tree" widgets would not have those widgets loaded if it's renamed
