### ISSUE TITLE
Jacoco is broken

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/shuffleboard#144]
Caused by #75 

https://stackoverflow.com/questions/39362955/gradle-jacoco-and-junit5

**Comment by JLLeitschuh** [comment]
Related:
https://github.com/gradle/gradle/issues/2702

**Comment by JLLeitschuh** [comment]
I have actually dedicated a bit of time to solving this. I'll try to get to it this week but I'm going on vacation on Friday evening through the following Friday so it may be a while.

**Comment by JLLeitschuh** [comment]
Caused by https://github.com/gradle/kotlin-dsl/issues/458
