### ISSUE TITLE
Unnecessary travis config as tests are running headless

### ISSUE THREAD

**Issue by JLLeitschuh** [wpilibsuite/shuffleboard#148]
This config below is only necessary if you are trying to run with a virtualized monitor:

```
before_install:
  - if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
    export DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    fi
```

Because the build is running headless with the monitor mocked in java this isn't necessary.

**Comment by ThadHouse** [comment]
This is obsolete with the change to azure, right?

**Comment by JLLeitschuh** [comment]
Probably, if you dropped the `.travis.yml` file.

**Comment by SamCarlberg** [comment]
OBE from #540
