### ISSUE TITLE
Changing team number/host doesn't clear NetworkTables

### ISSUE THREAD

**Issue by SamCarlberg** [wpilibsuite/shuffleboard#161]
When changing the NetworkTable server, entries are not cleared locally so every entry that existed on the previous host will be pushed to the new one

**Comment by AustinShalit** [comment]
@PeterJohnson What do you think?

**Comment by nightpool** [comment]
@samcarlburg this is probably the wrong issue for this project. If this is
the wrong behavior (which there appears to be some contention on) its a
fault of networktables, not us.

**Comment by SamCarlberg** [comment]
It's on us to make sure we clean up properly

**Comment by PeterJohnson** [comment]
The NetworkTable synchronization change will automatically clear anything that's not been written locally on connection to the server (if the server doesn't have the same key).  However, of it HAS been written locally, it will not be removed.  There are two questions here: 1. does the app write to values only when directed to by the user (which will make NT synchronization DTRT) and 2. do we want the app to clear everything out when the team number changes (not something NT keeps track of).  I think we want the answer to both of these to be yes.

**Comment by PeterJohnson** [comment]
Note this has to be done fairly carefully to avoid corrupting the other end.  You should stop the client, wait for it to disconnect, clear everything (including persistent values), then start the client against the new ip.

**Comment by PeterJohnson** [comment]
With the new instance API, this can be easier and safer depending on how your code is structured, as you can just create a new instance for the new team connection.

**Comment by AustinShalit** [comment]
I think a good plan of action for solving this issue it to wait until the instance API is merged and then solve it by spinning up a new instance.

**Comment by nightpool** [comment]
I would be wary about clearing the entire dashboard without prompting the user to at least save their layout. unless there's been a regression recently the answer to 1 is definitely yes.

I would generally expect most people to not have to change their host or team number, FWIW. Not sure how big of an issue this is.

**Comment by SamCarlberg** [comment]
The dashboard isn't cleared when sources are removed. The widgets are disabled, but that's all.

**Comment by nightpool** [comment]
This is currently a bug, and right now it has the workaround of restarting shuffleboard and connecting to the new host. 

If we start saving app preferences, this may become a bigger issue.

**Comment by bradamiller** [comment]
Seems like we can let this go until after beta. We just need to warn teams that they have shut down shuffleboard before changing the team number. When it comes up, set the new team number.

Once we add the preferences saving, then it will come back up to the same host and the NT cache problem will exist.

**Comment by SamCarlberg** [comment]
Fixed by #336
