### ISSUE TITLE
better default host

### ISSUE THREAD

**Issue by nightpool** [wpilibsuite/shuffleboard#162]
nearly noone will ever want to connect to localhost, we shouldn't optimize for it.

is there an mdns way to detect a robot automatically? could we use that value instead? otherwise, we should prompt for team number/host on startup if the value is empty

**Comment by AustinShalit** [comment]
Right now I think it will connect to the same robot as whatever the driver station is connected to.  I will test tomorrow when I have access to a roboRIO.

**Comment by ThadHouse** [comment]
NetworkTables itself will attempt to contact the robot directly by grabbing an IP from the currently running DS, although I don't know if this will happen directly now with the new instance stuff. It might have to explicitly be enabled, but I'd have to check.
