### ISSUE TITLE
Jenkins Build

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/shuffleboard#165]
We should start using Jenkins to build shuffleboard

**Comment by JLLeitschuh** [comment]
Why not just publish shuffleboard to Jfrog Artifactory and have jenkins pull down the newest version from that when building the eclipse plugins?

**Comment by AustinShalit** [comment]
When we build the plugins we want everything to be built using the latest versions of ntcore, wpiutil, ect.  The only way to guarantee this is to have Jenkins build it.
