### ISSUE TITLE
prompt to save layout when closing

### ISSUE THREAD

**Issue by nightpool** [wpilibsuite/shuffleboard#173]
Maybe should also keep track of whether the layout is unsaved/dirty? Doing that seems complicated.

**Comment by nightpool** [comment]
Possible approach: do JSON serialization, canonicalize, and compare to current layout. (or do a tree diff)

**Comment by SamCarlberg** [comment]
[I did something similar for GRIP](https://github.com/WPIRoboticsProjects/GRIP/pull/822), which heavily relies on the event bus model for knowing when a "save-changing" event occurs. The issue with shuffleboard is that we need to know when users change the scene graph as well as widget properties and layout preferences
