### ISSUE TITLE
API jar needs to be published

### ISSUE THREAD

**Issue by SamCarlberg** [wpilibsuite/shuffleboard#193]
Right now, we're only publishing the app uberjar as `edu.wpi.first.shuffleboard:Shuffleboard:<version>`

We should publish two jars: an API jar (may be an uberjar to give users access to guava etc.) and the fat app jar.

| Project | Artifact name |
|---|---|
| API | `shuffleboard-api` |
| APP | `shuffleboard-app-all` |

CC @JLLeitschuh

**Comment by JLLeitschuh** [comment]
Do you want to publish this as a maven artifact that other devs can pull down from some maven repo?

Do you want to simply have a JAR that devs pull down and use to compile against in their projects?

I would advocate going for the former (with maven), additionally, I would embed a "sample" project in this repository that plugin creators can use as a starting point for creating their own plugins. (All the gradle boilerplate stuff, ect...)

**Comment by SamCarlberg** [comment]
I think publishing the jar to the normal FRC maven coordinates (`first.wpi.edu/FRC/roborio/maven`) would be best. The shuffleboard app wouldn't use it, but plugin developers can use it as a compile-time dependency.

I've already put in some work on a skeleton project that's already set up with gradle and the code needed for pushing the jar to the local plugin directory
