### ISSUE TITLE
Problem with resizing text fields

### ISSUE THREAD

**Issue by bradamiller** [wpilibsuite/shuffleboard#203]
There is a very weird resizing thing with text fields  when the grid size if small (32x32). See attachment.

[Screen Recording 2017-09-28 at 4.35.46 PM.mov.zip](https://github.com/wpilibsuite/shuffleboard/files/1342269/Screen.Recording.2017-09-28.at.4.35.46.PM.mov.zip)

**Comment by SamCarlberg** [comment]
Fixed by #306
