### ISSUE TITLE
Property sheet for widgets should be on the context menu

### ISSUE THREAD

**Issue by bradamiller** [wpilibsuite/shuffleboard#212]
When double-clicking on a widget (a somewhat non intuitive operation) the widget area is replaced by it's property sheet. If the widget is small, the property sheet is unusable requiring the widget to be resized, then the property sheet edited, then double-click again, then the, now larger widget needs to be reduced to it's original size.

Instead, the property sheets should just be dialog boxes that pop up on a "Properties..." context menu entry. Then no resizing is required, and users don't have to learn the double-click gesture.

**Comment by SamCarlberg** [comment]
Similar to #46
