### ISSUE TITLE
loadSimpleWidget Test disabled

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/shuffleboard#214]
Take a look at my attempts to fix this here: https://github.com/wpilibsuite/shuffleboard/pull/204

For some reason, Jenkins refuses to run tests with GSON correctly.  So for now, I added a tag, `NonJenkinsTest`, that we should use for tests that use GSON and fail on Jenkins.  Hopefully, we come across a solution at some point.  This does mean we need to leave Travis CI & AppVeyor as required for build because they will be testing functionality that Jenkins does not.

**Comment by SamCarlberg** [comment]
This may be related to #358, which was fixed in #384

**Comment by carbotaniuman** [comment]
OBE. Disposition to close @PeterJohnson

**Comment by AustinShalit** [comment]
Why is this OBE?

**Comment by carbotaniuman** [comment]
We don't use Jenkins or Appveyor or Travis anymore?

**Comment by AustinShalit** [comment]
We should probably open a PR that removes the NonJenkins flag from all tests
