### ISSUE TITLE
The label for a widget inside a layout doesn't show with the ... on the left side

### ISSUE THREAD

**Issue by bradamiller** [wpilibsuite/shuffleboard#221]
The names of widgets placed directly in the grid show the rightmost part of the name if it is too big to fit. The names of widgets inside a list don't do that.

**Comment by SamCarlberg** [comment]
I think this is pretty minor:

1. Layouts are in scroll panes, so the text only wraps after ~28 characters (at minimum; this increases with tile width)
2. Subsystem widgets are the major usecase for layouts, and will automatically remove the leading subsystem name from the keys. I don't see component names exceeding that limit (eg `"Front Left Drive CAN Talon"` is 26, with spaces, and that's the longest I can think of)

**Comment by bradamiller** [comment]
Actually, as we talked about, I think it would be best to only have the final part of the network table key since the typical use case is doing things like SmartDashboard.putNumber("x", 5). In that case, it should really create a text field with a label of "x" and a value of 5. And leave off the front part of the path completely. I know it doesn't solve the case of putNumber("a/b/c", 4), but that's such a weird case and I think it would be OK just to call it "c".
