### ISSUE TITLE
Cache the Travis Docker Image to speed up builds

### ISSUE THREAD

**Issue by JLLeitschuh** [wpilibsuite/shuffleboard#222]
Related to #220 

The travis Docker image is built every time the CI system runs.
This adds about 80 seconds or so to the builds. This could be reduced if we took advantage of uploading docker containers or using travis's caching mechanism.

Example of how one user figured out how to cache docker containers in travis without uploading them to docker hub:
https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-248915326

**Comment by Moejoe90** [comment]
:+1:

**Comment by lastzero** [comment]
One of my images is about 4 GB and is getting downloaded every single time... room for optimization.

**Comment by SamCarlberg** [comment]
OBE from #540
