### ISSUE TITLE
Widget class names should all end with "widget"

### ISSUE THREAD

**Issue by SamCarlberg** [wpilibsuite/shuffleboard#264]
This would fix some headaches when trying to use UI controls that have the same or similar name to a widget

| Widget | Confused With | New Name |
|---|---|---|
| `NumberSlider` | `javafx.scene.control.Slider` | `NumberSliderWidget` |
| `ToggleButton` | `javafx.scene.control.ToggleButton` | `ToggleButtonWidget` |
| `ToggleSwitch` | `org.controlsfx.control.ToggleSwitch` | `ToggleSwitchWidget` |
| `TextView` | `TextField`, `TextArea` | `TextViewWidget` |
| `BooleanBox` | N/A | `BooleanBoxWidget` |
| `SpeedController` | N/A | `SpeedControllerWidget` |

**Comment by AustinShalit** [comment]
Should widgets be in their own package too?

**Comment by SamCarlberg** [comment]
They already are
