### ISSUE TITLE
Toggle switch widget moves outside of slider area

### ISSUE THREAD

**Issue by bradamiller** [wpilibsuite/shuffleboard#28]
When toggling a Toggle Switch widget it moves outside of the oval track on the right side. See attached screen shot.
<img width="158" alt="toggleswitch" src="https://user-images.githubusercontent.com/2307917/27509989-0a97d6a6-58d6-11e7-84b7-52e4a837f144.png">

**Comment by SamCarlberg** [comment]
I think this is a glitch with toggle sliders in general; it also happens with the playback "loop" slider

**Comment by SamCarlberg** [comment]
I've determined the culprit (but not the underlying cause). 

`api/src/main/resources/edu/wpi/first/shuffleboard/api/base.css`

```css
.tile {
    -fx-font-size: 11pt;
}
```

I can confirm the following behavior:

| Font size | Correct behavior? |
|---|---|
| 9pt | ✓
| 10pt | 
| 11pt | 
| 12pt | ✓
| 13pt | 
| 14pt |  
| 15pt | ✓
| 16pt | 
| 17pt | 
| 18pt | ✓
| 19pt | 
| 20pt |
| 21pt | ✓


Seems like it works in 3pt-increments? This is also definitely interacting weirdly with something else in the stylesheets (either `material` or `base`), as these font sizes all work with the default controlsfx stylesheets.

The easiest fix I can think of would to add this to the base stylesheet:

```css
.tile .toggle-switch {
    -fx-font-size: 12pt;
}
```

but that doesn't fix the problems with toggle switches _not_ in tiles that have their font sizes set, nor does it solve the issue of offscreen toggle switches in tile property sheets

**Comment by nightpool** [comment]
.toggle-switch {
    -fx-font-size: 12px !important;
}

?

**Comment by SamCarlberg** [comment]
That would lock all toggle switches to the same size, which I would prefer not to do
