### ISSUE TITLE
Widget titlebar probably should default to the root name

### ISSUE THREAD

**Issue by bradamiller** [wpilibsuite/shuffleboard#29]
The titlebar on widgets currently has the full path for the value. So a typical value would be "SmartDashboard/name". With small widgets, the name isn't shown because "SmartDashboard" fills the entire title area. Maybe show the full value when mousing over or in a properties dialog for the widget.

**Comment by SamCarlberg** [comment]
How should the name be displayed? Stuff under `/SmartDashboard` is easy, just use the entry key (`/SmartDashboard/Foo` -> `Foo`).

But what about the live window? Those can't be easily simplified. There can be stuff like `/LiveWindow/Subsystem A/Victor/Value` and `/LiveWindow/Subsystem B/Victor/Value`; both would simplify to `Value` (or `Victor` if we have a widget for speed controllers) and be impossible to tell apart by looking at the titles. Best case would be to simplify to `/Subsystem A/Victor/Value`, which is still long

**Comment by bradamiller** [comment]
Presumably the live window things will be grouped into subsystems like the current dashboard so there is no reason to show the full path since they will be labeled on the screen.
