### ISSUE TITLE
Add warning to edit grade-wrapper.properties in README

### ISSUE THREAD

**Issue by aswerdlow935** [wpilibsuite/shuffleboard#293]
Tried to shuffleboard with both Java JDK 8 & 9 installed (at least on a mac), and shuffleboard defaulted to Java JDK 9 even after gradle.property and bash_profile changes. However, adding `javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home` fixes the issue. A warning should be added in the README to add this property if running fails with the unknown 9.0.1 error message.

**Comment by JLLeitschuh** [comment]
More robust solution, before you run gradle, you just run this:
```bash
JAVA_HOME=`/usr/libexec/java_home -v 1.8`
```
or if you are using the Fish shell:
setenv -gx JAVA_HOME (/usr/libexec/java_home -v 1.8)

**Comment by aswerdlow935** [comment]
That also works just as well...thanks👌
