### ISSUE TITLE
Make graphs work with record/playback

### ISSUE THREAD

**Issue by bradamiller** [wpilibsuite/shuffleboard#301]
Graphs don't work with record/playback. Would probably be OK if they just started from wherever the play head was and worked going forward - not showing past history.

**Comment by SamCarlberg** [comment]
>  Would probably be OK if they just started from wherever the play head was and worked going forward - not showing past history.

This is the current behavior. Additionally, loading all data into a graph when a user scrubs through the timeline is prohibitively CPU expensive so I don't think we'll be making that particular change
