### ISSUE TITLE
Better support grouping by subsystem?

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/shuffleboard#314]
With automatic LiveWindow support, there are a LOT more widgets being added to LiveWindow.  Should there be an ability to group them better by subsystem?  Not sure how this can be done easily in the current graphical structure.

**Comment by PeterJohnson** [comment]
Actually, this was an error in wpilibsuite/allwpilib#771 where subsystems weren't getting type=LW Subsystem

**Comment by SamCarlberg** [comment]
All subsystems should just be classified as "Subsystem" anyway, since there's no difference between "Subsystem" and "LW Subsystem", and "PID Subsystem" just has an embedded PIDController that gets recognized anyway.

**Comment by PeterJohnson** [comment]
SmartDashboard requires it be "LW Subsystem", and so does Shuffleboard currently (otherwise the subsystem controls are not grouped).

**Comment by SamCarlberg** [comment]
SmartDashboard shows "Subsystem" with just a text field for a command to run, while "LW Subsystem" shows all of the components in the subsystem. I guess we can keep it as-is.
