### ISSUE TITLE
Plugin creation wiki page incorrectly uses 'runtime' instead of 'implementation' when defining Gradle dependency

### ISSUE THREAD

**Issue by 19lmyers** [wpilibsuite/shuffleboard#341]
I was following [this wiki page](https://github.com/wpilibsuite/shuffleboard/wiki/Plugins) to create a Shuffleboard plugin and found that the following instruction did not work:
```
dependencies {
    runtime group: 'edu.wpi.first.shuffleboard', name: 'api', version: '1.0.0'
}
```
Instead, I had to change it to this so Gradle could pull in the dependency in my IDE:
```
dependencies {
    implementation group: 'edu.wpi.first.shuffleboard', name: 'api', version: '1.0.0'
}
```

**Comment by SamCarlberg** [comment]
Thanks for pointing this out. I've since fixed it
