### ISSUE TITLE
Minor regression in MJPG Stream Viewer

### ISSUE THREAD

**Issue by bhjelstrom** [wpilibsuite/shuffleboard#352]
We post the limelight camera stream to NT such that it is visible to all dashboards (<ip>:5800). Shuffleboard, however, is the only dashboard that could not view the stream before we fixed this bug in our code:
In our initial connection header, we were including the "--" before the boundary name. 
I think this is technically our fault, but no other mjpg have had any trouble with the extra "--" included before the boundary name.

**Comment by PeterJohnson** [comment]
Yep, that's definitely not compliant with the MIME multipart/x-mixed-replace standard (https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html).  It looks like some other mjpg readers simply ignore the boundary setting in the initial connection header and take whatever comes after the first "--" as the boundary.

**Comment by ThadHouse** [comment]
This is actually a cscore issue, not a shuffleboard issue. We should move this to that repo.

**Comment by SamCarlberg** [comment]
This appears to have been fixed in a recent limelight update
