### ISSUE TITLE
Trailing space in IP causes NT errors

### ISSUE THREAD

**Issue by hkim** [wpilibsuite/shuffleboard#356]
`NT: connect() to 10.39.26.2  port 1735 timed out
`
a trailing space after the IP results in failure to connect to the Rio.

File -> Preferences -> NetworkTables -> Server

**Comment by AustinShalit** [comment]
@PeterJohnson Is this something that we should fix in shuffleboard or in ntcore?

**Comment by bradamiller** [comment]
I’d just delete the white space in ntcore rather than all programs that might pass IP addresses.

**Comment by PeterJohnson** [comment]
Closed by wpilibsuite/allwpilib#1516.
