### ISSUE TITLE
Increasing graphs refresh rate

### ISSUE THREAD

**Issue by Guym142** [wpilibsuite/shuffleboard#362]
Currently it seems that graphs update the plotted value only 10 times/sec while new data is sent to the dashboard up to 50 times/sec.
Was it done on purpose?
Is there a way to allow control of the refresh rate?

**Comment by SamCarlberg** [comment]
Check your code. Shuffleboard doesn't have any rate limiting so it'll update as soon as new data appears.

**Comment by PeterJohnson** [comment]
By default, NetworkTables only sends the data at a 10 Hz rate.  If you want more frequent updates you need to either change the NetworkTables update rate (using `NetworkTableInstance.setUpdateRate`) or flush explicitly by calling `NetworkTableInstance.flush`.
