### ISSUE TITLE
Custom plugins don't persist/load across resets

### ISSUE THREAD

**Issue by pjreiniger** [wpilibsuite/shuffleboard#377]
I made a custom widget (inside of a custom plugin) and got it to work in shuffleboard.  However, when I shut it down and save the config, the next time I load it up it complains that it can't find "MyCustomWidgets" setup information.  It appears the config file saves the widget I added, but not the custom plugin I loaded.

**Comment by SamCarlberg** [comment]
How did you load the plugin? If it's in a JAR in ~/Shuffleboard/plugins, it should be automatically loaded at startup (even if it wasn't loaded at the last shutdown -- this has been on my plate for a while).

If you loaded the plugin JAR from the "Load plugin" button on the plugins pane, shuffleboard doesn't remember at shutdown. This has also been on my plate for a while.

**Comment by pjreiniger** [comment]
Forgot to respond to this.  Originally I was using the "load plugin" button, but after you response switched to putting the jar where it really should be and it fixed my problem.  You seem to have the button issue tracked in #395, so this is good to close
