### ISSUE TITLE
Ability to control recordings through wpilib

### ISSUE THREAD

**Issue by jonathandao0** [wpilibsuite/shuffleboard#382]
A useful feature I would like to request is to add function calls into wpilib that would start/stop the recording feature on Shuffleboard. This would be useful so that I don't have to remember to manually start/stop a recording in order to specify what I want to see, as well as provide more control over what recordings I want (For example, if I wanted to record a specific period during TeleOp when my robot is actuating a mechanism.)

**Comment by AustinShalit** [comment]
Just building on this idea... I think that we mostly want to record whenever shuffleboard is open.  What if there was a way to put down markers when important actions are happening from user code.  That way you still have a full recording but also can quickly jump to the important part.
