### ISSUE TITLE
Shuffleboard Crash on Code Upload

### ISSUE THREAD

**Issue by ProfTechnical** [wpilibsuite/shuffleboard#391]
Somewhat frequently, when we are uploading code to the roboRIO, the Shuffleboard crashes. Obviously this is an inconvenience, since any unsaved subsystem widgets are lost and made default. If this could be fixed, it would be helpful.

**Comment by SamCarlberg** [comment]
Please post the log file at ~/Shuffleboard/shuffleboard.log after it crashes

**Comment by ProfTechnical** [comment]
[shuffleboard.log](https://github.com/wpilibsuite/shuffleboard/files/1692958/shuffleboard.log)

**Comment by SamCarlberg** [comment]
Looks like graph widgets aren't being properly reset when the robot program shuts down.
