### ISSUE TITLE
Dashboard Lockup on Robot Code Restart

### ISSUE THREAD

**Issue by Kython89** [wpilibsuite/shuffleboard#396]
Whenever we redeploy code to the RoboRio our dashboard locks up.  Part of the NetworkTables table viewer turns black and a majority of our values turn grey.  The only way to restore a functioning dashboard is to restart the dashboard.  We've attached a log and screenshot of this behavior.

![dashboard](https://user-images.githubusercontent.com/13496307/35756678-c77f2b4c-0831-11e8-8b5c-c32338a2feb8.png)
[shuffleboard.log](https://github.com/wpilibsuite/shuffleboard/files/1690959/shuffleboard.log)

**Comment by GaganBhat** [comment]
We have been able to replicate this. The exact same problem happens to us. The problem does not occur on smartDashboard though.

**Comment by SamCarlberg** [comment]
Looks like a duplicate of #391. Graph widgets aren't being properly reset

**Comment by Kython89** [comment]
@SamCarlberg Are you sure this is a duplicate of #391?  Our dashboard locks up and parts of it become unresponsive.  In #391 they state that their's crashes.

**Comment by SamCarlberg** [comment]
Different symptoms, but the same cause.
