### ISSUE TITLE
Refuses to Open

### ISSUE THREAD

**Issue by GaganBhat** [wpilibsuite/shuffleboard#397]
Hi, Shuffleboard used to work for me around a month ago, but recently it seems to just not open up at all. I am running Java version 8 update 162, so not sure if that changes anything at all. Opening through gradleRIO causes the crash as well.

**Comment by sciencewhiz** [comment]
What was the resolution?

**Comment by GaganBhat** [comment]
There wasn't any, the JAR still refuses to open, but I can now open it through GradleRio, so that's a good thing I guess. I wanted to collect more data before I opened an issue actively.

**Comment by AustinShalit** [comment]
What operating system are you on?

**Comment by GaganBhat** [comment]
Windows 10 Pro 64 Bit.
