### ISSUE TITLE
Widget tabs need scroll bars

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/shuffleboard#40]
See attached GIF

![ezgif-4-faec228fc1](https://user-images.githubusercontent.com/3799260/28378487-2e9496c8-6c65-11e7-9fb9-25d08d884103.gif)

**Comment by nightpool** [comment]
We should always shrink and grow the amount of tiles available based on the size of the window. Scroll bars aren't the solution here.

**Comment by SamCarlberg** [comment]
Functionally a duplicate of #7
