### ISSUE TITLE
Edit time scale for all graphs

### ISSUE THREAD

**Issue by aswerdlow935** [wpilibsuite/shuffleboard#402]
(Feature Request) to add a menu option that sets the timescale for all graphs (possibly per tab) so if one changes the timescale and wishes to make all graphs have the same timescale, it can be easily configured (as opposed to constantly changing each one).

**Comment by SamCarlberg** [comment]
The new settings dialogs from #482 helps with this. You can select all the graphs you want to edit and quickly move between them. It's not as easy as a global setting, but is an improvement over going to each graph individually and editing its settings.

**Comment by carbotaniuman** [comment]
@PeterJohnson Disposition to close.
