### ISSUE TITLE
Mecanum Drive appears inverted.

### ISSUE THREAD

**Issue by kschamplin19** [wpilibsuite/shuffleboard#404]
I am trying to use the Mecanum Drive base widget to display motor feedback.

An issue I ran into was that the Network Tables report inverted for the right side, even though the robot is operating correctly. This is because the MecanumDrive Class automatically reverses the right sides, causing errors with the visualization of the Drive Base widget.

Solution: In the widget code, invert the right motors.

**Comment by SamCarlberg** [comment]
This is more of a wpilib issue, since the MecanumDrive class doesn't invert the values set from NetworkTables.
