### ISSUE TITLE
Shuffleboard Is unusable without an internet connection

### ISSUE THREAD

**Issue by bot190** [wpilibsuite/shuffleboard#405]
The new update feature doesn't work correctly in situations without internet access. If you launch shuffleboard without an internet connection it complains that it is unable to connect to the update server. The modal that this error appears in doesn't have a way of closing it. This makes shuffleboard impossible to use without an internet connection. Something that seems extremely likely when connecting to robot wifi networks.

![shuffleboardrequiresinternet](https://user-images.githubusercontent.com/6110918/36064520-1f8388d2-0e5a-11e8-948b-76f78b6a1cd1.png)

**Comment by SamCarlberg** [comment]
This is intentional behavior to prevent users from accidentally closing the dialog and wondering why there's no update information. Press the escape button to close the dialog.

**Comment by bot190** [comment]
There should be a message saying that escape will close this dialog. This would require the user to read the dialog.
