### ISSUE TITLE
Shuffleboard Not Auto Loading When Opening DS

### ISSUE THREAD

**Issue by lolicopp** [wpilibsuite/shuffleboard#406]
When we switch our dashboard type to Shuffleboard, the interface doesn't load up. We made sure that our version of Java was not Java 9, we have Eclipse installed. I've looked around on CheifDelphi, and someone said to try putting quotes around the path of the Shuffleboard, but that didn't work either

There were a couple of posts about SmartDashboard, and so what we did was we replaced the SmartDashboard with Shuffleboard.jar. It still didn't work.

**Comment by sciencewhiz** [comment]
Did you figure it out? What was it?
