### ISSUE TITLE
Option to not show full source name in widget titles

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/shuffleboard#41]
There should be an option to only show the last part of a networktable path

![untitled](https://user-images.githubusercontent.com/3799260/28378585-837020ae-6c65-11e7-9f75-4d5b83d71298.jpeg)

**Comment by nightpool** [comment]
This used to be the behavior. I'm not exactly sure why it changed, but
yes—this is too much information by default.

**Comment by SamCarlberg** [comment]
@nightpool It never behaved like that. We could do this, but I'm not sure how useful it would be. There are almost never empty subtables like this unless ntcore is doing the initial server sync

**Comment by bradamiller** [comment]
I had made the same comment a few weeks ago. Maybe hovering over it could show the full path.

**Comment by bradamiller** [comment]
@SamCarlberg, I'm confused about your comment above. The "SmartDashboard" part of the path almost always obscures single tile widgets.

**Comment by SamCarlberg** [comment]
I was talking about the tree

**Comment by nightpool** [comment]
We can just show the leaf key name when after https://github.com/wpilibsuite/shuffleboard/issues/171 is implemented.

**Comment by SamCarlberg** [comment]
Fixed by #198
