### ISSUE TITLE
SingleEntryNetworkTableSource gets updates from unrelated entries

### ISSUE THREAD

**Issue by SamCarlberg** [wpilibsuite/shuffleboard#419]
Caused by this method in NetworkTableSource:

```java
protected final void setTableListener(TableListener listener) {
  NetworkTableInstance inst = NetworkTableInstance.getDefault();
  inst.removeEntryListener(listenerUid);
  setConnected(true);
  listenerUid = inst.addEntryListener(fullTableKey, (event) -> {
    // ...
    },
    0xFF);
  }
```

A listener created with `NetworkTableInstance.addEntryListener` is fired for *any* entry that starts with the given key. This causes single-key sources to be updated for unrelated values; for example:

NetworkTable key | Erroneously fired by
---|---
`/S` | `/SmartDashboard/Gyro angle`
`/U` | `/Unrelated`

**Comment by sataylor000** [comment]
Yep, we hit this yesterday while doing some debug.  Deleting the "unrelated" entry and re-adding it seemed to make it go away.
