### ISSUE TITLE
Recording file should not be .frc

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/shuffleboard#43]
This tool can be used for things other than frc.

**Comment by SamCarlberg** [comment]
Agreed. @nightpool thoughts?

**Comment by nightpool** [comment]
Yes this was a review comment I had on the original PR that we didn't fix.

.sblog maybe?

**Comment by nightpool** [comment]
`.sbr` 

@rrlapointe to take and work on

**Comment by AustinShalit** [comment]
@rrlapointe `.sbr`?

**Comment by SamCarlberg** [comment]
Closed by #179
