### ISSUE TITLE
Do not use the SmartDashboard directory

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/shuffleboard#44]
People may want to still use SmartDashboard.  Are we sure what we put in the directory will not conflict?

**Comment by SamCarlberg** [comment]
The plan is to replace the old dashboard with this one and stop supporting it. But there shouldn't be any conflicts, the only stuff that gets put in that directory by the old dashboard are the `save.xml` files and extension JARs. Shuffleboard is putting recording files and `save.json`

**Comment by bradamiller** [comment]
This seems somewhat presumptuous. Maybe we should wait until this is up, running, and people are happy with it before totally abandoning the old dashboard.

**Comment by nightpool** [comment]
I agree with brad, but either way I don't see any possible conflicts or
problems with reusing the old directory.

**Comment by bradamiller** [comment]
as long as it's using the same directly in a non-conflicting way.

**Comment by SamCarlberg** [comment]
There are no filename conflicts
