### ISSUE TITLE
Do not check for updates on the field

### ISSUE THREAD

**Issue by schnabel45** [wpilibsuite/shuffleboard#440]
Hello, FTA here. Please do not check for updates when shuffleboard is on the field. This can be accomplished by pinging the FMS server to verify it is available. If that is not achievable, put a nice big "Close this dialog" button on the message that says it is unable to check for updates. Pressing escape is not an acceptable solution to this. This is my third event on Saturday, and I'm just now learning how to dismiss that prompt, would have been nice to know this way sooner. The ultimate solution is, don't prompt at all.

**Comment by Kevin-OConnor** [comment]
Your teams should update to the latest shuffleboard which already has the difficult to dismiss dialog fixed.
