### ISSUE TITLE
Improve launching experience

### ISSUE THREAD

**Issue by schnabel45** [wpilibsuite/shuffleboard#441]
Hello, FTA here. Please improve the launching experience. When launching shuffleboard on the field we have no indication if the application is loading for near 60 seconds on some machines. A splash screen _could_ prevent this, but ultimately it takes way to long to load on slow machines (aka every computer distributed to rookies, or donated laptops).

**Comment by Kevin-OConnor** [comment]
Splash screen added in 1.3.1 via #445. Startup time logging added in #436 (to not erase logs) and #437. Startup time is definitely still an issue, but it's duped in #444 so I'm going to close this one.
