### ISSUE TITLE
Camera's don't auto-reconnect.

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/shuffleboard#443]
If the DriverStation goes to sleep with cameras connected, and then disconnected. Shuffleboard will not re-get the camera stream on re-connection. It's fixed by closing Shuffleboard and reopening it, but it's still annoying.

**Comment by Daltz333** [comment]
Some more information on my setup. Robot network is all static IPed, and camera servers on running on a Raspberry Pi3 using PyCScore. It works flawless in SmartDashboard and via the browser, and it only pops up occasionally using Shuffleboard.

**Comment by Daltz333** [comment]
Can I get a confirmation that I'm not the only one who sees this? I have replicated this on my personal laptop as well as two driver station laptops.

**Comment by Daltz333** [comment]
Any updates @SamCarlberg on this issue?

**Comment by SamCarlberg** [comment]
It's getting fixed upstream in cscore
