### ISSUE TITLE
Ver 1.3.0 not updating network tables from chooser

### ISSUE THREAD

**Issue by gearsincorg** [wpilibsuite/shuffleboard#447]
I'm posting here for the first time as I've just updated to rev 1.3 and my FRC Robot program behavior changed significantly.

It "appears" that selections that are being made on my Sendable Choosers are not getting propagated back to the robot. (as they used to be with a prior version)

In debugging this issue I have created mirror items which continually echo the currently selected value (as seen by the robot) back to the dashboard as individual items.

With SmartDashboard (clean slate) when I make a new selection in the chooser, the value is reflected immediately on the corresponding "selected" mirror item...  eg: when I choose a 4 second delay from the list of delay options, I see the "selected Delay" item change to 4.

However, with Shuffleboard, when I make the same selection, the Network table on the source side- panel changes, but the Echoed value does not.  

This implies to me that Shuffleboard is failing to send the selection change to the robot.
If I switch between SmartDashboard and Shuffleboard, the displayed values are consistent with this diagnosis.

Shuffleboard sees the values that the SmartDB sends but not the other way around.
This is occurring for a range of selected object type:  int, enum etc.

I will attach several logs.

[shuffleboard.2018-03-20-18.34.19.log.txt](https://github.com/wpilibsuite/shuffleboard/files/1831696/shuffleboard.2018-03-20-18.34.19.log.txt)
[shuffleboard.2018-03-20-20.14.42.log.txt](https://github.com/wpilibsuite/shuffleboard/files/1831697/shuffleboard.2018-03-20-20.14.42.log.txt)

**Comment by SamCarlberg** [comment]
Thanks for pointing this out so quickly! I've pushed a fix in v1.3.1 and should be available to the built in updater in the next 20 minutes
