### ISSUE TITLE
Close tab icon should be on the left side of the name

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/shuffleboard#45]
This way if I want to close a bunch of tabs really quickly, I can.

![ezgif-4-27f14ccd74](https://user-images.githubusercontent.com/3799260/28379033-28539136-6c67-11e7-930f-7a17b436c2b4.gif)

**Comment by SamCarlberg** [comment]
@nightpool

**Comment by AustinShalit** [comment]
I think you can mimic Safari's tab behavior here

**Comment by AustinShalit** [comment]
Also, the add tab button should not move either
