### ISSUE TITLE
Rotate camera views

### ISSUE THREAD

**Issue by Team3840** [wpilibsuite/shuffleboard#460]
Is it possible to add a property to rotate the camera image view in the camera stream input to the widget? As a CSA's we get ask this question frequently to be able to camera view rotation 180 or 90 from the hardware mounted position via software view.

![camerastream](https://user-images.githubusercontent.com/17012915/38331108-f0f57984-3817-11e8-98cf-0285b156a8ae.png)

**Comment by Team3840** [comment]
Excellence!  Is there a way we can test it?

**Comment by SamCarlberg** [comment]
You can clone the repository with

```
$ git clone https://github.com/wpilibsuite/shuffleboard
```

And check out the pull request with

```command-line
$ git fetch origin pull/478/head:rotate-camera
$ git checkout rotate-camera
```
