### ISSUE TITLE
POWER UP plugin should be removed

### ISSUE THREAD

**Issue by SamCarlberg** [wpilibsuite/shuffleboard#467]
There's no point in having the power up plugin when the 2019 season starts. The plugin should still be included until the 2018 offseason events are over. Probably looking at a November/December removal date.

**Comment by AustinShalit** [comment]
What is the game plan to have it available for download?

**Comment by SamCarlberg** [comment]
The plugin JAR should still be available on the maven server. We'll have to let people know in the 2019 release notes where to find it
