### ISSUE TITLE
Add LiveWindow support

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/shuffleboard#48]

**Comment by SamCarlberg** [comment]
All we would need to do is disable widgets that have data from the `/LiveWindow` table

**Comment by bradamiller** [comment]
I had thought that we would have a default tab that filters it's contents on the LiveWindow table. And the main default tab would filter on /SmartDashboard. Then if someone actually drags a widget from the LiveWindow path from the tree onto some pane, they would only see it updated when in Test mode.

**Comment by AustinShalit** [comment]
Closed by #113
