### ISSUE TITLE
Splashscreen has an ellipsis truncating the title

### ISSUE THREAD

**Issue by calcmogul** [wpilibsuite/shuffleboard#495]
**Describe the bug**  
The splashscreen isn't wide enough to display the title, so it gets truncated with an ellipsis.

**To Reproduce**  
1. Check out commit 1b916e79 (latest master as of 7/28/18)
2. `./gradlew :app:run`

**Expected behavior**  
The splashscreen should display the whole title.

**Screenshots**  
![wpilib-shufflebo](https://user-images.githubusercontent.com/2748555/43360322-754b5028-9268-11e8-9fc3-f56af91a421c.png)

Version v1.3.1-34-g1b916e7 built on July 28, 2018
JRE: 1.8.0_172-b11 -- Oracle Corporation
Operating system: Linux 4.17.9-1-ARCH amd64 (unknown distribution)

**Additional context**  
N/A

**Comment by SamCarlberg** [comment]
What's your screen resolution?

**Comment by calcmogul** [comment]
1920x1080

**Comment by SamCarlberg** [comment]
@calcmogul Can you apply this patch and see if the truncation remains? [preloader_patch.txt](https://github.com/wpilibsuite/shuffleboard/files/2294260/preloader_patch.txt)

**Comment by calcmogul** [comment]
That fixes it.
