### ISSUE TITLE
Tabs should be able to auto-populate 

### ISSUE THREAD

**Issue by SamCarlberg** [wpilibsuite/shuffleboard#51]
For example, a `SmartDashboard` tab should be able to auto-populate with one widget for each Network Table source that matches `^/SmartDashboard/.+$`, and  `LiveWindow` tab auto-populate with network table sources matching `^/LiveWindow/.+$`

Since every key can be a source and there's no point in having widgets for unchanging data like `/LiveWindow/Subsystem/Name` or `/LiveWindow/Subsystem/.type`, or for keys that are part of a composite object like a `SendableChooser`, the auto-population should be smart and not add widgets for those sources

**Comment by nightpool** [comment]
closed by #113
