### ISSUE TITLE
Automatic tab switching triggered from NetworkTables value change

### ISSUE THREAD

**Issue by ZanyHunter** [wpilibsuite/shuffleboard#511]
The ability to trigger tab switching via a NetworkTables value change would be very useful in FRC where screen space is limited and different tabs are needed for different parts of the game.

**Comment by andrewda** [comment]
Wow, this would be awesome! This definitely shouldn't _force_ the tab that's displayed, but I could see how a one-time "switch to tab 2" would be great super helpful.

**Comment by SamCarlberg** [comment]
[Related Chief Delphi thread](https://www.chiefdelphi.com/forums/showthread.php?t=166369)
