### ISSUE TITLE
Camera Widget fails to reconnect

### ISSUE THREAD

**Issue by Crossle86** [wpilibsuite/shuffleboard#534]
Robot is connected to DS PC and SB is responding to NT updates. Camera widget is feeding correctly. Disable robot and  power off. Power back on. When robot connects and starts updating NT, the other widgets respond to those updates but the camera feed is not reestablished. Must restart SB to get camera feed going again.

 - OS: Windows 10
 - Jdk 11
 - Version 1.3.1 downloaded from github recently.

**Comment by carbotaniuman** [comment]
Fixed in wpilibsuite/allwpilib#1513, disposition to close @AustinShalit
