### ISSUE TITLE
Save SB Window size and location

### ISSUE THREAD

**Issue by Crossle86** [wpilibsuite/shuffleboard#535]
SB always starts full screen. If you resize and reposition, that information is not saved. This is a problem since you have to resize SB to see the driver station window every time you start up.

Also, when DS starts, it does start SB, but SB does not display. It appears on the Windows taskbar and I  have to click it to get it to appear, which it does full screen.

Windows 10, Jdk 11, v1.3.1 recently downloaded from github and compiled locally.

**Comment by SamCarlberg** [comment]
This was added in #496. Window size and position are saved on a per-save basis.
