### ISSUE TITLE
SHUFFLEBOARD

### ISSUE THREAD

**Issue by arshacker** [wpilibsuite/shuffleboard#539]
**Describe the bug**  

**To Reproduce**  
1. ...
2. ...

**Expected behavior**  

**Screenshots**  

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Java version [e.g. 1.8.0_171]
 - Version [e.g. 1.3.1]

**Additional context**

**Comment by arshacker** [comment]
After loading a custom plugin I closed shuffleboard. When I try to open it again, I see the title screen saying, " Loading Camera Server plugin". Then the title screen disappears. and nothing else happens.

How can I get a working shuffleboard?

**Comment by arshacker** [comment]
Re my shuffleboard problem, Windows, java 1.8.0_181
  After loading a custom plugin I closed shuffleboard. When I try to open it again, I see the title screen saying, " Loading Camera Server plugin". Then the title screen disappears. and nothing else happens.
How can I get a working shuffleboard?

**Comment by SamCarlberg** [comment]
Check the most recent log files in the Shuffleboard directory in your home directory. The plugin is probably crashing when it's loaded

**Comment by AustinShalit** [comment]
@arshacker We are going to close this PR for now.  If you have more information, please reopen.
