### ISSUE TITLE
Camera Widget leaks memory

### ISSUE THREAD

**Issue by blucoat** [wpilibsuite/shuffleboard#544]
**Describe the bug**  
Creating a camera widget causes memory usage to rapidly increase, making the system unusable after a few minutes.

**To Reproduce**  
Connect to a camera stream and add a camera widget.  Then monitor shuffleboard's memory usage.

**Expected behavior**  
For shuffleboard to maintain relatively constant memory usage.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 on x86-64
 - Java version: OpenJDK 11 (build 11+24-Ubuntu-118.04)
 - Version: 2019.1.1-beta-2.

**Additional context**  
Commenting out [this line](https://github.com/wpilibsuite/shuffleboard/blob/6016fab3581889cb4de1aff57548086c01b8ca14/plugins/cameraserver/src/main/java/edu/wpi/first/shuffleboard/plugin/cameraserver/source/CameraServerSource.java#L254) makes the issue go away.    I suspect this is similar to #438.  The `Mat` gets cloned once per frame but is never freed, but since the memory is managed by native code Java doesn't think it needs to garbage collect.

**Comment by SamCarlberg** [comment]
Good catch
