### ISSUE TITLE
The default title on Graph widgets get the entire networktable address

### ISSUE THREAD

**Issue by KeithRieck** [wpilibsuite/shuffleboard#552]
**Describe the bug**  
When I use the builder interface to create a custom widget of type "Graph", the widget's title is the entire networktable address, instead of just the title I've requested.

**To Reproduce**  
    ShuffleboardTab debugTab = Shuffleboard.getTab("Debug");
    NetworkTableEntry visionDistWidget = debugTab
        .add("Vision Dist", 0.0)
        .withWidget("Graph")
        .getEntry();

**Expected behavior**  
I would expect to see a widget with the title "Vision Dist".  Instead, I see "Shuffleboad/Debug/Vision Dist".

![debug_shuffleboard_custom_tab](https://user-images.githubusercontent.com/5150205/49703992-68843980-fbd2-11e8-9d9c-f8b6f3430580.png)

**Comment by SamCarlberg** [comment]
Fixed by #556
