### ISSUE TITLE
Graphing values does not have consistent timestep

### ISSUE THREAD

**Issue by asid61** [wpilibsuite/shuffleboard#567]
![badgraph](https://user-images.githubusercontent.com/5743433/50567822-42981380-0cfe-11e9-84ce-f73b8694e38b.png)

^ picture of the issue. Shuffleboard randomly decides to stop graphing values for some time, then graphs a whole bunch at once. This behavior occurs whenever we are graphing encoder position, error, etc. on Shuffleboard in any timed loop (such as TeleopPeriodic).

**Comment by SamCarlberg** [comment]
What version of Shuffleboard do you experience this behavior with?

Since Shuffleboard graphs data as it arrives, having many data points bunched together all at once implies a possible network issue. Does this problem happen when connected over wifi or ethernet?

**Comment by asid61** [comment]
Version 1.3.1.
We used WiFi but we know it's not the Wi-Fi's fault, as switching to Smart Dashboard immediately resolves the problem. We experienced issues on several occasions, and it was always fixed by switching to Smart Dashboard.

**Comment by carbotaniuman** [comment]
@PeterJohnson Disposition to close.
