### ISSUE TITLE
Shuffleboard wont load layout with vscode wpi suite

### ISSUE THREAD

**Issue by NicholasBlackburn1** [wpilibsuite/shuffleboard#577]
shuffleboard will not load layout file even tho i updated vscode wpilib 
[shuffleboard.2019-01-15-11.17.47.log](https://github.com/wpilibsuite/shuffleboard/files/2760498/shuffleboard.2019-01-15-11.17.47.log)

**Comment by sciencewhiz** [comment]
Based on the log file, I think you're using 2019.1.1, not the latest 2019.2.1 which has some fixes for save file loading

**Comment by SamCarlberg** [comment]
Ah, good catch. This was fixed in #572.
