### ISSUE TITLE
withSize ignored.

### ISSUE THREAD

**Issue by blu28** [wpilibsuite/shuffleboard#595]
I am trying to write some strings to widgets on a new tab. Since the strings sometimes overrun the width of the widget, I wanted to specify that they should be wider than the default. I used this line to write to the shuffleboard:

          Shuffleboard.getTab("Status").add(fn, buf).withSize((length+15)/15, 1);

The String variables fn and buf have the title and value and the Integer length has the number of characters in the string. As a first take, I am assuming one column holds about 15 characters. However this always produces a widget that is still one column wide and one row high. 

**To Reproduce**  
1. Use the above line in robotinit to write a string longer than 15 characters.

**Expected behavior**  
I expected that strings longer than 15 characters would result in a widget that was more than one column wide.

 - Windows 10
 - OpenJDK 11.0.1+13
 - 2019.4.1

**Comment by SamCarlberg** [comment]
The withSize method requires a call to withPosition as well to avoid overlapping widgets.

I'll keep this issue open since shuffleboard really should be smarter with how it lays out  widgets
