### ISSUE TITLE
Video Stream (camera) not showing in its widget

### ISSUE THREAD

**Issue by tom131313** [wpilibsuite/shuffleboard#597]
**Describe the bug**  

**To Reproduce**  
1. ...
2. ...

**Expected behavior**  

**Screenshots**  

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Java version [e.g. 1.8.0_171]
 - Version [e.g. 1.3.1]

**Additional context**

**Comment by tom131313** [comment]
Most of our Shuffleboard tabs and widgets are created and updated on the roboRIO which is also the NetworkTables server.  Video streams are being generated on a Raspberry Pi (frcvision v2019.3.1).
```java
      VideoSource Bcamera = startCamera(config);

      Map<String, Object> mapBumperCamera = new HashMap<String, Object>();
      mapBumperCamera.put("Show crosshair", false);
      mapBumperCamera.put("Show controls", false);
                
      Main.obj.cameraTab.add("Bumper Camera", Bcamera)
          .withWidget(BuiltInWidgets.kCameraStream)
          .withPosition(20, 0)
          .withSize(13, 13)
          .withProperties(mapBumperCamera)
          ;
```
The live video will not play in the widget unless the following statement is included with the above code:
```java
      NetworkTableEntry fake = Main.obj.cameraTab.add("fakeB", "x")
           .withSize(2, 2)
           .withPosition(1, 1)
           .getEntry()
           ;
```
then the video plays.  This irritating behavior can't possibly be intended.

**Comment by PeterJohnson** [comment]
Your rPi is also the NT server?  So you're running without a RoboRIO?  I think there's Shuffleboard-specific stuff done in the robot main loop that isn't present on the rPi loop.

**Comment by tom131313** [comment]
The roboRIO is the NT server.  We have tried it without a roboRIO and used the RPi as a NT server and it does exactly the same strange behavior.

**Comment by tom131313** [comment]
You are right - on the roboRIO we get a free
```java
Shuffleboard.update()
```
Thanks for your help and all the camera server stuff you have provided for us to use.
