### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by OccultSlolem** [wpilibsuite/shuffleboard#614]
**Describe the bug**  
There is a dead link in the wiki for the documentation regarding plugins. [This is the offending link.](http://first.wpi.edu/FRC/roborio/release/docs/shuffleboard/api/edu/wpi/first/shuffleboard/api/plugin/Plugin.html) I tried Internet Archive to see if there was an old version of the page available but to no avail sadly.

**To Reproduce**  
1. Go to the [plugins documentation](https://github.com/wpilibsuite/shuffleboard/wiki/Plugins)
2. Click [this link](https://first.wpi.edu/FRC/roborio/release/docs/shuffleboard/api/edu/wpi/first/shuffleboard/api/plugin/Plugin.html)
3. Observe the resulting 404 error

**Expected behavior**  
The page should appear properly

**Screenshots**  
https://pasteboard.co/Ifl5ss7.png

 - Chrome 74.0.3729.157

**Comment by carbotaniuman** [comment]
Disposition to close @AustinShalit
