### ISSUE TITLE
ShadowJars published to maven always include linux binaries in addition to platform binaries

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/shuffleboard#615]
I noticed when trying to test Win32 shadowjar generation with a 64 bit jdk that the 64 bit binaries were being included in the final Jar. Looking at the maven artifacts, I noticed that the linux binaries are included in the Windows and mac jars. I think the reason why is the shadowjar plugin is including the build platform binaries because theyre part of the `compile` configuration, but also included the specified output platforms. I tried looking at a way to fix this, but the kotlin DSL kept getting in the way, and I wasn't able to figure out a solution.

**Comment by carbotaniuman** [comment]
@PeterJohnson Disposition to close.
