### ISSUE TITLE
Don't pause graphs when value isn't changing

### ISSUE THREAD

**Issue by Oblarg** [wpilibsuite/shuffleboard#620]
Graph widgets will currently freeze if the value stops changing.  This means that a constant graph will effectively never be displayed, and the graph will "jump" jarringly when the value finally does change.  This makes Shuffleboard graphs somewhat frustrating to use.

**Comment by Starlight220** [comment]
I slightly disagree with this. A graph that is updated and has a constant value should be shown as a straight line, but a graph that isn't updated should not change. The problem is implementing this.

**Comment by carbotaniuman** [comment]
Implemented in chart-fx update. Disposition to close @PeterJohnson.
