### ISSUE TITLE
Bottom bar is huge and non-resizable

### ISSUE THREAD

**Issue by prateekma** [wpilibsuite/shuffleboard#628]
**Describe the bug**  
The bottom bar of Shuffleboard with the "NetworkTables: Connected" and play/pause buttons is massive and cannot be resized.

**To Reproduce**  
1. Open Shuffleboard 2020 Beta 1

**Expected behavior**  

The bar should be way smaller and resizable.

**Screenshots**  

![image](https://user-images.githubusercontent.com/19977330/67125713-6c55f480-f1c3-11e9-8802-a5f4069a9463.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Java version [e.g. 11.0.4]
 - Version [e.g. 2020.1.1-beta-1]

**Additional context**  
None

**Comment by AustinShalit** [comment]
Bisecting shows that the first bad commit is: https://github.com/wpilibsuite/shuffleboard/commit/504fd947e14d114e9b2bc19fd06dcc846fff4d37

**Comment by SamCarlberg** [comment]
This typically happens when a widget fails to load and breaks the library view. Can you attach the log file?

@prateekma

**Comment by ThadHouse** [comment]
@SamCarlberg we figured out it was opencv not loading correctly. #609 fixes it.

**Comment by ThadHouse** [comment]
Closed by #609
