### ISSUE TITLE
SendableChooser empty on startup instead of showing default value

### ISSUE THREAD

**Issue by trevnels** [wpilibsuite/shuffleboard#639]
**Describe the bug**  
When Shuffleboard starts after robot code is restarted, Sendable Choosers with a default value set programmatically do not show this default value on the dashboard. They instead show empty with a ! symbol. Internally, the chooser's active value is the default, but this is not represented on Shuffleboard.

ComboBox Choosers show completely blank with the !. SplitBox Choosers have the correct item highlighted but still show a !. When switching from Combo to Split and back to Combo, the correct item is indeed in the box, but still has the !.

**To Reproduce**  
1. Create a SendableChooser with a default option, and send it to Shuffleboard
2. With Shuffleboard closed, start robot code
3. Open Shuffleboard

The SendableChooser will be blank instead of showing the default/active value.

**Expected behavior**  
When Shuffleboard starts, SendableChooser widgets should be set to the currently active value instead of being empty.

**Screenshots**  
[Imgur Album](https://imgur.com/a/qUds1mf)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Java version 11.0.1+13-LTS
 - Version 2020.1.1-beta4

**Additional Context**
My guess is that some sort of an update method isn't being called when the widget is created when it needs to be.

**Comment by trevnels** [comment]
I believe the issue is that the listener [here](https://github.com/wpilibsuite/shuffleboard/blob/master/plugins/base/src/main/java/edu/wpi/first/shuffleboard/plugin/base/widget/ComboBoxChooserWidget.java#L43) is not being called on widget initialization. If I can fix it myself, I'll open a PR.

**Comment by trevnels** [comment]
Fixed in #640

**Comment by sciencewhiz** [comment]
Thanks for the PR. However, the fixed issues shouldn't be closed until the PR is merged.
