### ISSUE TITLE
NullPointerException When Loading Themes from Plugin

### ISSUE THREAD

**Issue by Russell-Newton** [wpilibsuite/shuffleboard#643]
**Describe the bug**  
I am trying to create a plugin that includes a custom theme. When I place the .jar file into the plugins folder, Shuffleboard crashes when opening. The log file says that there is a `NullPointerException` that occurs when I create a new Theme object. I believe that it is related to the `localClass` parameter of the Theme constructor.

**To Reproduce**  
1. Place a plugin .jar file into ~/Shuffleboard/plugins
          * The plugin must attempt to create a new Theme object (with the constructor that takes a class reference) and export it with `getThemes()`.
2. Attempt to open Shuffleboard

**Expected behavior**  
I would expect that the plugin can load properly. Even if it can't find the style sheet, I wouldn't expect there to be a `NullPointerException` in the Theme constructor.

**Screenshots**  
![image](https://user-images.githubusercontent.com/18690062/73087035-cd1a5a80-3e9f-11ea-8663-f9d2be555fb1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 10.0 amd64
 - Java version 11.0.4+11 -- AdoptOpenJDK
 - Version 2020.2.2

**Additional context**  
The same error occurs when I try to load in the example custom-theme plugin.

**Comment by carbotaniuman** [comment]
Closed by #645. Disposition to close @PeterJohnson

**Comment by carbotaniuman** [comment]
@PeterJohnson Disposition to close.
