### ISSUE TITLE
Dead values remain in shuffleboard

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/shuffleboard#655]
Each time we open the Shuffleboard there are many values that are not updated from code, and we have to clear and replace only what we want. Is there a way to clear all "dead" values from the shuffleboard?

**Comment by Daltz333** [comment]
Shuffleboard relies on NT, and NT doesn't clear "old" values.

**Comment by Daltz333** [comment]
```
Shuffleboard does remove nt values when it disconnects. More likely that person has it set to autoload an old layout that has widgets for data that's no longer being sent
```

**Comment by Starlight220** [comment]
Will check next time I load it, thanks!
