### ISSUE TITLE
Update PIDController widget to new PIDController class

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/shuffleboard#660]
Update the PID widget to the new PIDController, mainly the `enable` part.

**Comment by sciencewhiz** [comment]
Since the old PID Controller has not been removed, I don't think the Shuffleboard PID Controller widget should only support the new widget. Either a new widget should be created (and the wpilib new PID Controller updated to use it) or the documentation should be updated to cover the differences.

**Comment by carbotaniuman** [comment]
@PeterJohnson Disposition to close - won't fix.

**Comment by PeterJohnson** [comment]
Actually, we just had a discussion on this, and the thought was we would update this widget and add a backwards compatibility widget for the old PIDController.
