### ISSUE TITLE
The tile grid should add or remove rows and columns as it's resized

### ISSUE THREAD

**Issue by SamCarlberg** [wpilibsuite/shuffleboard#7]
Currently the amounts of rows and columns are hardcoded. Columns should be added or removed as the tile grid is resized, possibly down to some fixed minimum size or to a size where anything smaller would clip or remove tiles

**Comment by bradamiller** [comment]
If we remove rows and columns as the window is resized, what will happen to the widgets that are in those rows and columns?

**Comment by nightpool** [comment]
They would get compresses if possible. If not possible, we should add
scrollbars then, yes
