### ISSUE TITLE
shuffleboard won't start

### ISSUE THREAD

**Issue by jpfrigeriogithub** [wpilibsuite/shuffleboard#719]
Hi!  I have followed the directions for installing the WPILib tools here:
https://docs.wpilib.org/en/stable/docs/zero-to-robot/step-2/wpilib-setup.html

But shuffleboard won't start, crashes every time.  It flashes some messages ("loading camera server", etc), but then quits.

This is a fully updated Windows 10 laptop.
I have fully uninstalled all previous versions.
I have updated java and .net, all are current.
I have uninstalled and re-installed a few times with several reboots.
Nothing seems to help.
I have also checked the windows event viewer to see if the exception thrown was caught there, but it's blank.

Glad for any tips you might have.  
Thanks.

**Comment by ThadHouse** [comment]
Just to double check, you're not using an N version of windows, right?

**Comment by jpfrigeriogithub** [comment]
No, straight windows 10, came preinstalled.  64-bit.

**Comment by sciencewhiz** [comment]
Does it work if you run from the command line `c:\Users\Public\wpilib\2022\jdk\bin\java -jar c:\Users\Public\wpilib\2022\tools\shuffleboard.jar`

**Comment by jpfrigeriogithub** [comment]
Yes, thanks!

I guess that means the problem is in the shuffleboard.vbs file that the
shortcut calls.

I tried to run that from the command line to see if it gave any helpful
diagnostics.  But it didn't, it failed just as before and spit out nothing
to the console at all.

Hopefully I'm a one-off and it's not a bug affecting too many people. :-)

thanks again.

**Comment by calcmogul** [comment]
We've narrowed this down to the application crashing after the script exits when the application can't write to stdout or stderr. The Python script can be fixed by setting stdout and stderr to subprocess.DEVNULL, but I don't know what the equivalent for VBS is.

**Comment by sciencewhiz** [comment]
Can you try replacing `c:\Users\Public\wpilib\2022\tools\shuffleboard.jar` with the file linked below and then run with the shortcut? This has a candidate change to not write to stdout/stderr as mentioned above.

https://wpilib.jfrog.io/artifactory/wpilib-generic-local/shuffleboard-test/shuffleboard-allwpilib3919/shuffleboard.jar

**Comment by sciencewhiz** [comment]
This fix was included in WPILib 2022.2.1 release

**Comment by PeterJohnson** [comment]
Closing, please reopen if there is still an issue.
