### ISSUE TITLE
Shuffleboard crashes frequently on MacOS

### ISSUE THREAD

**Issue by bovlb** [wpilibsuite/shuffleboard#736]
**Describe the bug**  
Shuffleboard will start up, connect to the robot, and display results, but will then crash within a few minutes.  

**To Reproduce**  
1. Install latest WPILIB on MacOS
2. Launch shuffleboard from VS Code using "Start Tool"
3. Wait a few minutes

**Expected behavior**  
Shuffleboard should be usable for a three hour programming session.

**Desktop (please complete the following information):**
 - OS: Mac OS X 12.5.1 x86_64
 - Java version 11.0.13+8 Eclipse Adoptium
 - Version 2022.4.1

**Comment by bovlb** [comment]
[Archive.zip](https://github.com/wpilibsuite/shuffleboard/files/9779629/Archive.zip)
diag files

**Comment by bovlb** [comment]
I installed 2023.2.1 today and was able to run ShuffleBoard for a three-hour session without a single crash.  I didn't see anything in the change notes about crashing less, but this is an order of magnitude better.

**Comment by Starlight220** [comment]
There were multiple changes between 2022 and 2023 regarding how macos artifacts are handled; I expect that's what fixed it.

Can this be closed?

**Comment by bovlb** [comment]
I have not seen this issue in the 2023 season.
