### ISSUE TITLE
Showing negative numbers as progress bars doesn't work

### ISSUE THREAD

**Issue by bradamiller** [wpilibsuite/shuffleboard#80]
Showing negative numbers as progress bars does the cylon eyes thing - very cool, but probably not what was expected.

**Comment by SamCarlberg** [comment]
You have to set the minimum bound. It defaults to zero.

**Comment by nightpool** [comment]
???

**Comment by bradamiller** [comment]
so is that behavior intended to be a warning that I have to do that? Shouldn't it do something else, like display the number in red or display some sort of error?

**Comment by nightpool** [comment]
To be more clear

 - add a new number as a progress bar
 - make that number negative
 - see a weird scrolling animation thing that is very confusing
