### ISSUE TITLE
remove progress bar widget

### ISSUE THREAD

**Issue by nightpool** [wpilibsuite/shuffleboard#84]
negative vs positive values should be clear from a glance

![image](https://user-images.githubusercontent.com/233815/28852349-62f9cdf2-76f6-11e7-9522-e126cbc5da1f.png)

**Comment by SamCarlberg** [comment]
We should add a `LinearIndicator` widget. Would be easy to do

**Comment by nightpool** [comment]
Remove progress bar widget and replace it with Linear Indicators

**Comment by nightpool** [comment]
right now we have VoltageView which uses a linear indicator component, we should add a standalone linear indicator widget.

**Comment by AustinShalit** [comment]
@rrlapointe
